#!/usr/bin/env bash

###################################################################################################

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DATE="$(date "+%B %e, %Y")"

MANUAL_NAME="manual_example"
MANUAL_IN_DIR=$DIR/$MANUAL_NAME
MANUAL_OUT_DIR=$DIR/output/$MANUAL_NAME

###################################################################################################

error=0

echo ""
mkdir -p $MANUAL_OUT_DIR

# Generate HTML, ODT and PDF documents from Markdown plain text files
echo "Creating HTML manual..."
pandoc --self-contained -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o $MANUAL_OUT_DIR/$MANUAL_NAME.html
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate manual in HTML format."
    echo ""
fi
echo "Creating ODT manual..."
pandoc -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o $MANUAL_OUT_DIR/$MANUAL_NAME.odt
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate manual in ODT format."
    echo ""
fi
echo "Creating PDF manual..."
pandoc -H "${MANUAL_IN_DIR}/tex_to_pdf_style.tex" --top-level-division=chapter -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o $MANUAL_OUT_DIR/$MANUAL_NAME.pdf
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate manual in PDF format."
    echo ""
fi

echo ""
if [ $error -eq 3 ]; then
    echo "Error: Manual can't be created."
    rm -rf $MANUAL_OUT_DIR
else
    echo "Generated Manual placed at: ${MANUAL_OUT_DIR}"
fi
echo ""

exit 0
