#!/usr/bin/env bash

###################################################################################################

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DATE="$(date '+%Y_%m_%d')"
DOC_DATE="$(date "+%B %e, %Y")"

DOC_NAME=$1
DOC_IN_DIR=$DIR/$DOC_NAME
DOC_OUT_DIR=$DIR/export/$DATE/$DOC_NAME

###################################################################################################

error=0

echo ""

# Check if name of document to be generated has been provided
if [ $# -lt 1 ]; then
    echo "You need to provide the document name to be generated."
    echo "  Example:"
    echo "    pandoc_export document_dir_name"
    echo ""
    exit 1
fi

# Check and remove directory slash (/) of document name
if [[ "${DOC_NAME: -1}" == "/" ]]; then
    DOC_NAME=${DOC_NAME::-1}
fi

# Check if Pandoc is installed
pandoc -v &> /dev/null
if [[ $? != 0 ]]; then
    echo "Error: Pandoc not found."
    echo "Please install it through \"pandoc_install\" script."
    echo ""
    exit 1
fi

# Create output directory
mkdir -p $DOC_OUT_DIR

# Generate HTML, ODT and PDF documents from Markdown plain text files
echo "Creating HTML document..."
pandoc --embed-resources --standalone -M date="${DOC_DATE}" $DOC_IN_DIR/*.md -f markdown -s \
        -o $DOC_OUT_DIR/$DOC_NAME.html
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate document in HTML format."
    echo ""
fi
echo "Creating ODT document..."
pandoc -M date="${DOC_DATE}" $DOC_IN_DIR/*.md -f markdown -s -o $DOC_OUT_DIR/$DOC_NAME.odt
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate document in ODT format."
    echo ""
fi
echo "Creating PDF document..."
pandoc -H "${DOC_IN_DIR}/tex_to_pdf_style.tex" --top-level-division=chapter \
        --columns=100 -M date="${DOC_DATE}" $DOC_IN_DIR/*.md -f markdown -s \
        -o "${DOC_OUT_DIR}/${DOC_NAME}.pdf"
if [[ $? != 0 ]]; then
    ((error=error+1))
    echo "Error: Can't generate book in PDF format."
    echo ""
fi

echo ""
if [ $error -ge 3 ]; then
    echo "Error: document can't be created."
    rm -rf $DOC_OUT_DIR
else
    echo "Generated document placed at: ${DOC_OUT_DIR}"
fi
echo ""

exit 0
