#!/usr/bin/env bash

###################################################################################################

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

DOC_NAME=$1
DOC_OUT_DIR=$DIR/export/$DOC_NAME

###################################################################################################

echo ""

# Check if name of document to be generated has been provided
if [ $# -lt 1 ]; then
    echo "You need to provide the document name to be removed."
    echo "  Example:"
    echo "    ./pandoc_rm document_dir_name"
    echo ""
    exit 1
fi

# Check and remove directory slash (/) of document name
if [[ "${DOC_NAME: -1}" == "/" ]]; then
    DOC_NAME=${DOC_NAME::-1}
fi

# Remove Generated Document
rm -rf $DOC_OUT_DIR
echo "Document removed: ${DOC_OUT_DIR}"
echo ""

exit 0
