#!/usr/bin/env bash

###################################################################################################

# Constants
PANDOC_DEB_PKG="https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb"

# Variables
help=0
apt=0

###################################################################################################

# For each argument
for i in "$@"
do
    # Convert it to Lowercases
    i=`echo "$i" | tr A-Z a-z`

    # Check for expected arguments
    if [ "$i" == "-h" ] || [ "$i" == "--help" ]; then
        help=1
    elif [ "$i" == "-a" ] || [ "$i" == "--apt" ]; then
        apt=1
    else
        echo "Ignoring unexpected argument: $i"
    fi
done

###################################################################################################

# Show help information
if [ $help -eq 1 ]; then
    printf "This script install Pandoc and all requeriments for Markdown Workbench usage.\n"
    printf "\n"
    printf "Usage: pandoc_install [-h --help] [-a --apt]\n"
    printf "\n"
    printf " -h, --help  : Show this message.\n"
    printf " -f, --apt : Use APT for Pandoc install instead installing it from Github.\n"
    printf "\n"
    exit 0
fi

###################################################################################################

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

###################################################################################################

echo ""
echo "Installing Markdown-Pandoc Workbench Requeriments..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
apt-get update
echo ""

# Install LaTex
echo "-------------------------------------------------"
echo " Installing LaTex packages (texlive-latex-base,  "
echo " texlive-latex-extra, texlive-xetex)             "
echo "-------------------------------------------------"
apt-get -y install texlive-latex-base
if [[ $? != 0 ]]; then
    echo "Error: Can't install texlive-latex-base package."
    echo ""
    exit 1
fi
echo ""
apt-get -y install texlive-latex-extra
if [[ $? != 0 ]]; then
    echo "Error: Can't install texlive-latex-extra package."
    echo ""
    exit 1
fi
echo ""
apt-get -y install texlive-xetex
if [[ $? != 0 ]]; then
    echo "Error: Can't install texlive-xetex package."
    echo ""
    exit 1
fi
echo ""

# Install SVG to PDF converter
echo "-------------------------------------------------"
echo " Installing SVG to PDF converter package         "
echo " (librsvg2-bin)                                  "
echo "-------------------------------------------------"
apt-get -y install librsvg2-bin
if [[ $? != 0 ]]; then
    echo "Error: Can't install librsvg2-bin package."
    echo ""
    exit 1
fi
echo ""

# Install Pandoc
echo "-------------------------------------------------"
echo " Installing pandoc package (pandoc)              "
echo "-------------------------------------------------"
if [ $apt -eq 1 ]; then
    apt-get -y install pandoc
    if [[ $? != 0 ]]; then
        echo "Error: Can't install pandoc package."
        echo ""
        exit 1
    fi
else
    apt-get -y install wget
    if [[ $? != 0 ]]; then
        echo "Error: Can't install wget package."
        echo ""
        exit 1
    fi
    echo ""
    wget $PANDOC_DEB_PKG
    if [[ $? != 0 ]]; then
        echo "Error: Can't download Pandoc package from:"
        echo "${PANDOC_DEB_PKG}"
        echo ""
        exit 1
    fi
    apt-get -y remove pandoc
    dpkg -i ./pandoc*.deb
    if [[ $? != 0 ]]; then
        echo "Error: Can't install Pandoc debian package."
        rm -f ./pandoc*.deb
        echo ""
        exit 1
    fi
    rm -f ./pandoc*.deb
fi
echo ""

# Check if Pandoc was successfully installed
pandoc -v &> /dev/null
if [[ $? != 0 ]]; then
    echo "Error: Pandoc not found."
    echo "Seems that something goes wrong."
    echo ""
    exit 1
fi

echo "Markdown-Pandoc Workbench Requeriments successfully installed."
echo ""

exit 0
