#!/usr/bin/env bash

###################################################################################################

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

MANUAL_NAME=$1
MANUAL_OUT_DIR=$DIR/export/$MANUAL_NAME

###################################################################################################

echo ""

# Check if name of manual to be generated has been provided
if [ $# -lt 1 ]; then
    echo "You need to provide the manual name to be generated."
    echo "  Example:"
    echo "    ./generate_manual manual_example"
    echo ""
    exit 1
fi

# Check and remove directory slash (/) of manual name
if [[ "${MANUAL_NAME: -1}" == "/" ]]; then
    MANUAL_NAME=${MANUAL_NAME::-1}
fi

# Remove Generated Manual
rm -rf $MANUAL_OUT_DIR
echo "Manual removed: ${MANUAL_OUT_DIR}"
echo ""

exit 0
