#!/usr/bin/env bash

###################################################################################################

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

MANUAL_NAME="manual_example"
MANUAL_OUT_DIR=$DIR/output/$MANUAL_NAME

###################################################################################################

echo ""
rm -rf $MANUAL_OUT_DIR
echo "Manual removed: ${MANUAL_OUT_DIR}"
echo ""

exit 0
